version: "3"
services:
  jokeapp:
    image: outisa/docker-app-exercise15
    ports:
      - 5000:5000
    container_name: jokeapp
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
