version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
  docker: circleci/docker@1.0.0
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter
  deploy:
    jobs:
      - docker/publish:
          image: outisa/docker-app-exercise15
          tag: 'latest'
