version: 2.1
orbs:
  deploy-to-heroku: betterdoc/deploy-to-heroku@4.1.0
  docker: circleci/docker@1.0.0
workflows:
  deploy:
    jobs:
      - docker/publish:
          image: outisa/docker-app-exercise15
          tag: 'latest'
      - deploy-to-heroku:
          app-name: 'jokeapp-for-docker-exercise'
          app-type: 'web'
