version: 2.1
orbs:
  heroku: circleci/heroku@1.2.1
  docker: circleci/docker@1.0.0
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          post-steps:
            - run:  heroku container:release web
          pre-steps:
            - run: heroku container:push web     
  deploy:
    jobs:
      - docker/publish:
          image: outisa/docker-app-exercise15
          tag: 'latest'
