version: 2.1
orbs:
  heroku: circleci/heroku@1.2.1
  docker: circleci/docker@1.0.0
workflows:
  heroku_deploy:
    jobs:
      - deploy:
        executor: heroku/default
        steps:
          - checkout
          - heroku/install
          - run:
              command: >
                heroku container:push -app $HEROKU_APP_NAME web
              command: > 
                heroku container:release -app $HEROKU_APP_NAME web
          - heroku/deploy-via-git          
  deploy:
    jobs:
      - docker/publish:
          image: outisa/docker-app-exercise15
          tag: 'latest'
