version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1
  docker: circleci/docker@1.0.0
jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: pushing to heroku
          command: |
            heroku container:login
            heroku container:push --app $HEROKU_APP_NAME web
            heroku container:release --app $HEROKU_APP_NAME web
            heroku container:logout
workflows:
  heroku_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master    
  deploy:
    jobs:
      - docker/publish:
          image: outisa/docker-app-exercise15
          tag: 'latest'
